# Generated by Django 4.1.2 on 2022-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('tg_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('chosen_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('state', models.IntegerField()),
                ('gender', models.CharField(choices=[('f', 'Жіноча'), ('m', 'Чоловіча'), ('o', 'Інша')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='recipe_photo')),
            ],
        ),
    ]
